// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StephenJoshFinalProject.Models;

namespace StephenJoshFinalProject.Migrations.StephenJoshFinalProject2
{
    [DbContext(typeof(StephenJoshFinalProject2Context))]
    [Migration("20181207022005_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StephenJoshFinalProject.Models.CoffeeShopLogin", b =>
                {
                    b.Property<string>("CoffeeShopLoginId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("StoreCode");

                    b.HasKey("CoffeeShopLoginId");

                    b.ToTable("CoffeeShopLogin");
                });
#pragma warning restore 612, 618
        }
    }
}
